// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserBase struct {
	UserID       int64       `json:"user_id"`
	UserEmail    string      `json:"user_email"`
	UserHash     string      `json:"user_hash"`
	UserPassword string      `json:"user_password"`
	UserOtp      string      `json:"user_otp"`
	IsVerified   pgtype.Bool `json:"is_verified"`
	IsDeleted    pgtype.Bool `json:"is_deleted"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type UserProfile struct {
	UserID       int64       `json:"user_id"`
	UserEmail    string      `json:"user_email"`
	UserNickname string      `json:"user_nickname"`
	UserFullname pgtype.Text `json:"user_fullname"`
	UserAvatar   pgtype.Text `json:"user_avatar"`
	UserMobile   pgtype.Text `json:"user_mobile"`
	UserGender   pgtype.Bool `json:"user_gender"`
	UserBirthday pgtype.Date `json:"user_birthday"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type UserSession struct {
	SessionID      uuid.UUID          `json:"session_id"`
	UserID         int64              `json:"user_id"`
	RefreshToken   string             `json:"refresh_token"`
	UserAgent      string             `json:"user_agent"`
	ClientIp       string             `json:"client_ip"`
	IsBlocked      bool               `json:"is_blocked"`
	UserLoginTime  pgtype.Timestamptz `json:"user_login_time"`
	UserLogoutTime pgtype.Timestamptz `json:"user_logout_time"`
	ExpiresAt      time.Time          `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
}
